-- Q1. What is the total revenue generated by male vs. female customers?

Select gender, Sum(purchase_amount) as revenue
From customer
Group By gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 

Select customer_id, purchase_amount
From customer
Where discount_applied = 'Yes' And purchase_amount >= ( Select Avg(purchase_amount) from customer );

-- Q3. Which are the top 5 products with the highest average review rating?

Select item_purchased, Round(Avg(review_rating),2) as 'Average Product Rating'
From customer
Group By item_purchased
Order By Avg(review_rating) desc
Limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

Select shipping_type, Round(Avg(purchase_amount),2) as avg_purchase_amount
From customer 
Where shipping_type in ('Standard','Express')
Group By shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.

Select subscription_status, Count(customer_id) as total_customer,
Round(Avg(purchase_amount),2) as average_spend,
Round(Sum(purchase_amount),2) as total_revenue 
From customer 
Group By subscription_status
Order By average_spend, total_revenue;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

Select item_purchased,
Round(100 * Sum(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END )/ Count(*),2) as discount_rate
From customer 
Group By item_purchased 
Order By discount_rate desc 
Limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.

with customer_type as ( 
Select customer_id, previous_purchases, 
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Retuening'
    ELSE 'Loyal' END as customer_segment
From customer ) 
Select customer_segment, Count(*) as 'Number of customers'
From customer_type
Group By customer_segment;

-- Q8. What are the top 3 most purchased products within each category?

with item_counts as (
Select category, item_purchased,
Count(customer_id) as total_orders,
Row_number() over(partition by category order by count(customer_id) desc ) as item_rank 
From customer 
Group By category, item_purchased )
Select category, item_purchased, total_orders,item_rank
From item_counts 
Where item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

Select subscription_status,
Count(customer_id) as 'repeat buyers'
From customer 
Where previous_purchases > 5
Group By subscription_status;

-- Q10. What is the revenue contribution of each age group?

Select age_group,
Sum(purchase_amount) as total_revenue
From customer
Group by age_group
Order By total_revenue desc; 
